### ISSUE TITLE
Using local images

### ISSUE THREAD

**Issue by yulioaj290** [gaetanozappi/react-native-avatar-social#1]
**Is your feature request related to a problem? Please describe.**
When you need to load images from local storage, the current code is triyng to use `uri: ` format.

**Describe the solution you'd like**
On the `AvatarSocial.js` class you should use generic image loading to allow images from local storage and from network too.

**Describe alternatives you've considered**

**Additional context**

**Comment by gaetanozappi** [comment]
Hi @yulioaj290 , I have uploaded version 0.0.3 as requested.
Let me know if there are any problems or if it doesn't work properly.
